### PR TITLE
Enable partition filtering in shuffle expressions

### PR DESCRIPTION
**Pull request by rjzamora**
Ports `SimpleShuffle` and it's sub-classes to `PartitionsFiltered`.

### CODE REVIEW

**Comment by mrocklin** [comment]
I haven't deeply reviewed this (and may not).  I'm curious, how did it feel when using `PartitionsFiltered`?

**Comment by rjzamora** [comment]
>I haven't deeply reviewed this (and may not). I'm curious, how did it feel when using PartitionsFiltered?

Using `PartitionsFiltered` was not particularly difficult in this case (we already needed to think through it once for HLGs).

**Comment by rjzamora** [comment]
>I haven't deeply reviewed this (and may not).

I took a few passes over this PR and cleaned things up a bit.  There aren't any dramatic changes IMO, so I'll probably merge today if you don't mind.

**Comment by mrocklin** [comment]
No objection.  At this stage I'm mostly going to be very picky about the structure of how we define algorithms, but pretty laissez faire about the algorithms themselves

**Pull request merged**
