### PR TITLE
Add basic `Expr.visualize` method

### PR DESCRIPTION
**Pull request by rjzamora**
**Example**

```python
from dask_expr.datasets import timeseries

df = timeseries()
df["id2"] = df["id"] * 2
df2 = (df[df["id"] < 1000].shuffle("id2", backend="tasks")["x"]).partitions[0]
df2.simplify().visualize()
```

Screen Shot 2023-04-26 at 2 15 22 PM

### CODE REVIEW

**Comment by mrocklin** [comment]
Cool.  Quick thought, maybe we replace a term if it is repeated in the children?

So rather than ...

```
LT(Projection, 1000)
    Projection(...)
```

Maybe we have

```
LT( -- , 1000)
    Projection(...)
```

Just a thought, not a constraint

**Comment by rjzamora** [comment]
>maybe we replace a term if it is repeated in the children?

I can understand the appeal of doing that. However, I actually find it useful for the label to include just enough information for the graph to be self explanatory, and using `" -- "` would not make something like `LT( -- , -- )` very clear.  In fact, I wonder if we should number the expressions, and use something like `" #2 "` instead of `" -- "`.

Thoughts on something like this?:

Screen Shot 2023-04-26 at 3 37 43 PM

**Comment by rjzamora** [comment]
Or perhaps we go with something like `" -- "` (as you suggest) and rely on "tooltips" to show more-detailed information about dependencies.

**Comment by mrocklin** [comment]
I think I like your original use of the operation names over numbers.  Happy to drop the `--` thought.

**Comment by rjzamora** [comment]
>I think I like your original use of the operation names over numbers. Happy to drop the -- thought.

Okay. This PR is only mean to provide minimal `visualize` support, so I'm expecting us to revisit most of the details :)

**Comment by rjzamora** [comment]
@mrocklin - Any objections on merging this as is with the knowledge that we will probably change things later?

**Comment by mrocklin** [comment]
Do your thing.  Sorry to be MIA.  Lots of conference booth time this week.

**Pull request merged**
